# Generated by Django 4.1.7 on 2023-05-09 22:46

from django.db import migrations
from ..models import Operations, Policy
from django.contrib.contenttypes.models import ContentType


def populate_policies(apps, schema_editor):
    content_types = ContentType.objects.all()

    # Create a policy for each content type and operation
    for content_type in content_types:
        for operation in Operations:
            policy = Policy(ContentType=content_type, Operation=operation)
            policy.save()


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_policies),
    ]
