# Generated by Django 4.1.7 on 2023-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_password_defined",
            field=models.BooleanField(default=False),
        ),
    ]
