# Generated by Django 4.1.7 on 2023-04-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_is_password_defined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_password_defined",
        ),
        migrations.AddField(
            model_name="customuser",
            name="define_password_token",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
