# Generated by Django 4.1.7 on 2023-05-08 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_groups"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="groups",
            new_name="group",
        ),
    ]
