# Generated by Django 4.1.7 on 2023-03-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("roomsreservations", "0001_initial"),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="datetime",
        ),
        migrations.AddField(
            model_name="meeting",
            name="reservation",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="roomsreservations.roomreservation",
            ),
            preserve_default=False,
        ),
    ]
