# Generated by Django 4.1.7 on 2023-05-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="notifiedMeetingInHalfHour",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="notifiedMeetingTomorrow",
            field=models.BooleanField(default=False),
        ),
    ]
