# Generated by Django 4.1.5 on 2023-02-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
