# Generated by Django 4.1.5 on 2023-02-05 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_student_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
    ]
